services:
  myjournal.api:
    image: myjournal.api
    env_file:
      - .env
    build:
      context: .
      dockerfile: MyJournal.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://*:80/;http://*:8080/;https://*:443/;https://*:8081/
    ports:
      - "8081:80"
      - "8082:443"
    volumes:
      - ~/.aspnet/https:/https:ro