version: '3.9'
services:
  myjournal.api:
    image: myjournal.api
    env_file:
      - .env
    build:
      context: .
      dockerfile: MyJournal.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "8081:80"
      - "8082:443"
    volumes:
      - ~/.aspnet/https:/https:ro